server:
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB

application:
  security:
    jwt:
      private_key: ${PRIVATE_KEY}
      public_key: ${PUBLIC_KEY}
      passphrase: ${PASSPHRASE}
      access_token_exp: 7200000
      refresh_token_exp: 864000000


cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}