server:
  servlet:
    context-path: /api/v1
  port: 9090

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB

  okta:
    oauth2:
      issuer: https://dev-hfi4jmuzqkrtvgrz.us.auth0.com/
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}
      scope: openid+profile+email


