server:
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB

application:
  security:
    jwt:
      private_key: ${PRIVATE_KEY}
      public_key: ${PUBLIC_KEY}
      passphrase: ${PASSPHRASE}
      access_token_exp: 7200
      refresh_token_exp: 604800

